MvcBlog/Controllers/AdminMakaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBlog.Models;
using System.Web.Helpers;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace MvcBlog.Controllers
{
    public class AdminMakaleController : Controller
    {
        mvcblogEntities db = new mvcblogEntities();
        //
        // GET: /AdminMakale/
        public ActionResult Index(int Page=1)
        {
            var makales = db.Makales.OrderByDescending(m=>m.MakaleId).ToPagedList(Page,10);
            return View(makales);
        }

        //
        // GET: /AdminMakale/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /AdminMakale/Create
        public ActionResult Create()
        {
            ViewBag.KategoriId = new SelectList(db.Kategoris, "KategoriId", "KategoriAdi"); 
            return View();
        }

        //
        // POST: /AdminMakale/Create
        [HttpPost]
        public ActionResult Create(Makale makale, string etiketler, HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makale.Foto = "/Uploads/MakaleFoto/" + newfoto;
                }

                if (etiketler != null)
                {
                    string[] etiketdizi = etiketler.Split(',');
                    foreach (var i in etiketdizi)
                    {
                        var yenietiket = new Etiket { EtiketAdi = i };
                        db.Etikets.Add(yenietiket);
                        makale.Etikets.Add(yenietiket);
                    }
                }
                makale.UyeId = Convert.ToInt32(Session["uyeid"]);
                makale.Okunma = 1;
                db.Makales.Add(makale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
               return View(makale);
        }

        //
        // GET: /AdminMakale/Edit/5
        public ActionResult Edit(int id)
        {
            var makale = db.Makales.Where(m => m.MakaleId==id).SingleOrDefault();
            if (makale==null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriId = new SelectList(db.Kategoris, "KategoriId", "KategoriAdi", makale.KategoriId);
            return View(makale);
        }

        //
        // POST: /AdminMakale/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase Foto,Makale makale)
        {
            try
            {
                var makales = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
                if (Foto!=null)
                {
                    if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(makales.Foto));
                    }
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makales.Foto = "/Uploads/MakaleFoto/" + newfoto;
                    makales.Baslik = makale.Baslik;
                    makales.Icerik = makale.Icerik;
                    makales.KategoriId = makale.KategoriId;
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /AdminMakale/Delete/5
        public ActionResult Delete(int id)
        {
            var makale = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
            if (makale==null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        //
        // POST: /AdminMakale/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var makales = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
                if (makales == null)
                {
                    return HttpNotFound();
                }

                if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                {
                    System.IO.File.Delete(Server.MapPath(makales.Foto));
                }

                foreach (var i in makales.Yorums.ToList())
                {
                    db.Yorums.Remove(i);
                }
                foreach (var i in makales.Etikets.ToList())
                {
                    db.Etikets.Remove(i);
                }
                db.Makales.Remove(makales);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcBlog/Views/AdminMakale/Create.cshtml
@model MvcBlog.Models.Makale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="card-body">
        <h2>Yeni Makale</h2>

        @using (Html.BeginForm("Create", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.KategoriId, "KategoriId", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("KategoriId", String.Empty)
                        @Html.ValidationMessageFor(model => model.KategoriId)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Baslik, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Baslik)
                        @Html.ValidationMessageFor(model => model.Baslik)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Icerik, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Icerik)
                        @Html.ValidationMessageFor(model => model.Icerik)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Foto, new { @class = "form-control col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="Foto" id="Foto" accept=".jpg,.jpeg,.png,.svg,.bmp,.gif,.JPEG,.PNG" class="form-control" />
                        @Html.ValidationMessageFor(model => model.Foto)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tarih, new { @class = "form-control col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tarih, "date")
                        @Html.ValidationMessageFor(model => model.Tarih)
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Etiketler", new { @class = "form-control col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBox("Etiketler")
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Kaydet" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Geri Dön", "Index")
        </div>
</div></div>

MvcBlog/Views/AdminMakale/Delete.cshtml
@model MvcBlog.Models.Makale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="card-body">
        <h3>Bu makaleyi silmeyi onaylıyor musunuz?</h3>
        <div class="col-sm-12">
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Baslik)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Baslik)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Icerik)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Icerik)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Foto)
                </dt>

                <dd>
                    <img src="@Model.Foto" width="150" alt="" />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Tarih)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tarih)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UyeId)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UyeId)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Okunma)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Okunma)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Kategori.KategoriAdi)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Sil" class="btn btn-default" /> |
                    @Html.ActionLink("Geri Dön", "Index")
                </div>
            }
        </div>
    </div>
</div>

MvcBlog/Views/AdminMakale/Edit.cshtml
@model MvcBlog.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="card-body">
        <h2>Makale Düzenle</h2>

        @using (Html.BeginForm("Edit", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Makale</h4>
                <hr />
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.MakaleId)

                <div class="form-group">
                    @Html.LabelFor(model => model.KategoriId, "KategoriId", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("KategoriId", String.Empty)
                        @Html.ValidationMessageFor(model => model.KategoriId)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Baslik, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Baslik)
                        @Html.ValidationMessageFor(model => model.Baslik)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Icerik, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Icerik)
                        @Html.ValidationMessageFor(model => model.Icerik)
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Geçerli Foto", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <img width="75" src="@Model.Foto" alt="" />
                        @Html.ValidationMessageFor(model => model.Foto)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Foto, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="Foto" id="Foto" accept=".jpg,.jpeg,.png,.svg,.bmp,.gif,.JPEG,.PNG" class="form-control" />
                        @Html.ValidationMessageFor(model => model.Foto)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tarih, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tarih)
                        @Html.ValidationMessageFor(model => model.Tarih)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Kaydet" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Geri Dön", "Index")
        </div>
</div></div>

MvcBlog/Views/AdminMakale/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<MvcBlog.Models.Makale>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="card-body">
        <h2>Makale Yönetimi</h2>
        <hr />
        <button class="button font-weight-bold">
            @Html.ActionLink("Yeni Makale Oluştur", "Create")
        </button>
        <hr />
        <table class="table">     
            <tr>
                <th>
                    @Html.Label("Makale Başlık")
                </th>
                <th>
                    @Html.Label("İmaj")
                </th>
                <th>
                    @Html.Label("Tarih")
                </th>
                <th>
                    @Html.Label("Üye Adı")
                </th>
                <th>
                    @Html.Label("Okunma")
                </th>
                <th>
                    @Html.Label("Kategori Adı")
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a href="/Home/MakaleDetay/@item.MakaleId">@item.Baslik</a>
                    </td>
                    <td>
                        <img width="75" src="@item.Foto" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tarih)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UyeTablo.AdSoyad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Okunma)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kategori.KategoriAdi)
                    </td>
                    <td>
                        @Html.ActionLink("Düzenle", "Edit", new { id = item.MakaleId }) |
                        @*@Html.ActionLink("Detaylar", "Details", new { id=item.MakaleId }) |*@
                        @Html.ActionLink("Sil", "Delete", new { id = item.MakaleId })
                    </td>
                </tr>
            }

        </table>
    </div>
    <!-- Pagination -->
    <div class="row">
        <div class="col-md-8 text-center">
            <div class="pagedList pagination">
                @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }), PagedListRenderOptions.Classic)
            </div>
        </div>
    </div>
</div>